<?php
declare(strict_types=1);

class ThemeManager
{
    private static array $themes = [];
    private static string $defaultTheme = 'beige-cream';

    public static function init(): void
    {
        $config = require __DIR__ . '/themes.php';
        self::$themes = $config['themes'] ?? [];
        self::$defaultTheme = $config['defaultTheme'] ?? 'beige-cream';
    }

    public static function getThemeNames(): array
    {
        $names = [];
        foreach (self::$themes as $key => $theme) {
            $names[$key] = [
                'name' => $theme['name'],
                'description' => $theme['description'] ?? '',
            ];
        }
        return $names;
    }

    public static function getCurrentTheme(): string
    {
        if (session_status() === PHP_SESSION_ACTIVE && !empty($_SESSION['theme'])) {
            if (isset(self::$themes[$_SESSION['theme']])) {
                return $_SESSION['theme'];
            }
        }
        return self::$defaultTheme;
    }

    public static function setCurrentTheme(string $themeKey): bool
    {
        if (!isset(self::$themes[$themeKey])) {
            return false;
        }
        if (session_status() === PHP_SESSION_ACTIVE) {
            $_SESSION['theme'] = $themeKey;
        }
        return true;
    }

    public static function generateCSSVariables(string $mode = 'light'): string
    {
        $themeKey = self::getCurrentTheme();
        $theme = self::$themes[$themeKey] ?? self::$themes[self::$defaultTheme];
        $colors = $theme[$mode] ?? $theme['light'] ?? [];

        $css = ":root,\nhtml[data-theme=\"{$themeKey}\"][data-mode=\"{$mode}\"] {\n";
        foreach ($colors as $var => $value) {
            $css .= "  {$var}: {$value};\n";
        }
        $css .= "}\n";
        return $css;
    }

    public static function generateFullCSS(): string
    {
        $css = "/* Auto-generated by ThemeManager */\n\n";

        foreach (self::$themes as $key => $theme) {
            foreach (['light', 'dark'] as $mode) {
                if (!isset($theme[$mode])) continue;
                $selector = "html[data-theme=\"{$key}\"][data-mode=\"{$mode}\"]";
                $css .= "{$selector} {\n";
                foreach ($theme[$mode] as $var => $value) {
                    $css .= "  {$var}: {$value};\n";
                }
                $css .= "}\n\n";
            }
        }

        /* Applied overrides on body */
        $css .= "body {
  background-color: var(--bg-primary);
  color: var(--text-primary);
  transition: background-color 0.4s ease, color 0.4s ease;
}
";

        $css .= ".glass-panel {
  background: var(--glass-bg);
  backdrop-filter: blur(12px);
  border: 1px solid var(--glass-border);
}
";

        $css .= ".gradient-text {
  background: var(--gradient-hero);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
";

        $css .= ".nav-link::after {
  background: linear-gradient(90deg, var(--accent-primary), var(--accent-secondary));
}
";

        $css .= ".medical-grid {
  background-image:
    linear-gradient(var(--wave-color-1) 1px, transparent 1px),
    linear-gradient(90deg, var(--wave-color-1) 1px, transparent 1px);
  background-size: 20px 20px;
}
";

        return $css;
    }

    public static function injectThemeScript(): string
    {
        $currentTheme = self::getCurrentTheme();
        $allThemes = array_keys(self::$themes);
        $themeNames = [];
        foreach (self::$themes as $key => $t) {
            $themeNames[$key] = $t['name'];
        }

        $json = htmlspecialchars(json_encode([
            'themes' => $allThemes,
            'themeNames' => $themeNames,
            'current' => $currentTheme,
        ]), ENT_QUOTES, 'UTF-8');

        return <<<HTML
<script nonce="{{NONCE}}">
(function() {
    var cfg = {$json};
    var saved = localStorage.getItem('regenmed_theme');
    var savedMode = localStorage.getItem('regenmed_mode');
    var theme = saved && cfg.themes.indexOf(saved) !== -1 ? saved : cfg.current;
    var mode = savedMode || (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    document.documentElement.setAttribute('data-theme', theme);
    document.documentElement.setAttribute('data-mode', mode);
    if (mode === 'dark') document.documentElement.classList.add('dark');
    else document.documentElement.classList.remove('dark');
    window.__regenmedTheme = { themes: cfg.themes, themeNames: cfg.themeNames };
})();
</script>
HTML;
    }

    public static function themeColorSwatch(string $themeKey): string
    {
        $theme = self::$themes[$themeKey] ?? null;
        if (!$theme) return '';
        $light = $theme['light'] ?? [];
        $primary = $light['--accent-primary'] ?? '#0d9488';
        $secondary = $light['--accent-secondary'] ?? '#06b6d4';
        $green = $light['--accent-green'] ?? '#16a34a';
        $violet = $light['--accent-violet'] ?? '#7c3aed';
        return <<<HTML
<span style="display:inline-flex;gap:2px;align-items:center;">
  <span style="width:10px;height:10px;border-radius:50%;background:{$primary};"></span>
  <span style="width:10px;height:10px;border-radius:50%;background:{$secondary};"></span>
  <span style="width:10px;height:10px;border-radius:50%;background:{$green};"></span>
  <span style="width:10px;height:10px;border-radius:50%;background:{$violet};"></span>
</span>
HTML;
    }
}

ThemeManager::init();
